# Site settings
title: Helmcken Market
email:
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Helmcken Market, the premier locally-owned and operated
  grocers in Victoria, BC!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Helmcken Market
email: helmcken38@yahoo.ca
facebook_username: HelmckenMarket
twitter_username: helmckenmarket
github_username:
address:
  - line: 38 Helmcken Road
  - line: Victoria, BC V8Z 5G7
  # Feel free to add more lines here 
hours: 9:00am to 9:00pm Daily
telephone: +1 250-479-1818
copyright:

# API settings
google_api_key: "AIzaSyCzENpC5tqfhGi4x89dYSPswJA_MOMcYAA"

# Build settings
markdown: kramdown
